[project]
name = "narwhals-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2025.7.0",
    "narwhals>=2.1.1",
    "pandas>=2.3.1",
    "polars>=1.32.2",
]
